FROM ruby:2.6
LABEL maintainer="u6k.apps@gmail.com"

WORKDIR /var/myapp/
COPY pkg/ pkg/

RUN apt-get update && \
    apt-get -y upgrade && \
    apt-get clean && \
    gem install specific_install && \
    gem specific_install https://github.com/u6k/crawline.git && \
    gem install pkg/*

ENTRYPOINT ["investment-horse-racing-crawler"]
