require "timecop"
require "webmock/rspec"

require "spec_helper"

RSpec.describe InvestmentHorseRacing::Crawler::Parser::OddsTrioPageParser do
  before do
    WebMock.enable!

    @downloader = Crawline::Downloader.new("investment-horse-racing-crawler/#{InvestmentHorseRacing::Crawler::VERSION}")

    # Setup data
    InvestmentHorseRacing::Crawler::Model::RaceMeta.destroy_all

    ## 2018-06-24 hanshin no 1 race result data
    url = "https://keiba.yahoo.co.jp/race/result/1809030801/"
    WebMock.stub_request(:get, url).to_return(
      status: [200, "OK"],
      body: File.open("spec/data/result.20180624.hanshin.1.html").read)

    parser = InvestmentHorseRacing::Crawler::Parser::ResultPageParser.new(url, @downloader.download_with_get(url))
    parser.parse({})

    @meta = InvestmentHorseRacing::Crawler::Model::RaceMeta.find_by(race_id: "1809030801")

    ## 2018-06-24 hanshin 1R odds trio page parser
    @url = "https://keiba.yahoo.co.jp/odds/sf/1809030801/"
    WebMock.stub_request(:get, @url).to_return(
      status: [200, "OK"],
      body: File.open("spec/data/odds_trio.20180624.hanshin.1.html").read)

    @parser = InvestmentHorseRacing::Crawler::Parser::OddsTrioPageParser.new(@url, @downloader.download_with_get(@url))

    WebMock.disable!
  end

  describe "#redownload?" do
    context "2018-06-24 hanshin 1R odds trio page" do
      it "redownload if newer than 30 days" do
        Timecop.freeze(Time.local(2018, 7, 24, 10, 4, 0)) do
          expect(@parser).to be_redownload
        end
      end

      it "do not redownload if over 30 days old" do
        Timecop.freeze(Time.local(2018, 7, 24, 10, 5, 0)) do
          expect(@parser).not_to be_redownload
        end
      end
    end
  end

  describe "#related_links" do
    context "2018-06-24 hanshin 1R odds trio page" do
      it "is odds pages" do
        expect(@parser.related_links).to contain_exactly(
          "https://keiba.yahoo.co.jp/odds/tfw/1809030801/",
          "https://keiba.yahoo.co.jp/odds/ur/1809030801/",
          "https://keiba.yahoo.co.jp/odds/wide/1809030801/",
          "https://keiba.yahoo.co.jp/odds/ut/1809030801/",
          "https://keiba.yahoo.co.jp/odds/st/1809030801/")
      end
    end
  end

  describe "#parse" do
    context "2018-06-24 hanshin 1R odds trio page" do
      it "is odds trio info" do
        context = {}

        @parser.parse(context)

        expect(context).to be_empty

        expected = build_have_attributes

        expect(InvestmentHorseRacing::Crawler::Model::OddsTrio.all).to match_array(expected)
      end

      it "overwrite when existing data" do
        meta_11111 = InvestmentHorseRacing::Crawler::Model::RaceMeta.create(race_id: "11111")
        meta_22222 = InvestmentHorseRacing::Crawler::Model::RaceMeta.create(race_id: "22222")

        InvestmentHorseRacing::Crawler::Model::OddsTrio.create(race_meta: meta_11111, horse_number_1: 1, horse_number_2: 1, horse_number_3: 1, odds: 111.11)
        InvestmentHorseRacing::Crawler::Model::OddsTrio.create(race_meta: meta_22222, horse_number_1: 2, horse_number_2: 2, horse_number_3: 2, odds: 222.22)
        InvestmentHorseRacing::Crawler::Model::OddsTrio.create(race_meta: @meta,      horse_number_1: 3, horse_number_2: 3, horse_number_3: 3, odds: 333.33)

        context = {}

        @parser.parse(context)

        expect(context).to be_empty

        expected = build_have_attributes
        expected << have_attributes(race_meta_id: meta_11111.id, horse_number_1: 1, horse_number_2: 1, horse_number_3: 1, odds: 111.11)
        expected << have_attributes(race_meta_id: meta_22222.id, horse_number_1: 2, horse_number_2: 2, horse_number_3: 2, odds: 222.22)

        expect(InvestmentHorseRacing::Crawler::Model::OddsTrio.all).to match_array(expected)
      end
    end

    context "valid page on web" do
      it "parse success" do
        parser = InvestmentHorseRacing::Crawler::Parser::OddsTrioPageParser.new(@url, @downloader.download_with_get(@url))

        context = {}

        parser.parse(context)

        expect(context).to be_empty

        expect(InvestmentHorseRacing::Crawler::Model::OddsTrio.count).to be > 0
      end
    end

    def build_have_attributes
      [
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 3, odds: 153.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 4, odds: 202.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 5, odds: 329.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 6, odds: 545.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 7, odds: 1398.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 8, odds: 308.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 9, odds: 210.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 10, odds: 2124.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 11, odds: 4594.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 12, odds: 89.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 13, odds: 2732.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 14, odds: 52.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 15, odds: 237.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 2, horse_number_3: 16, odds: 1993.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 4, odds: 230.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 5, odds: 354.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 6, odds: 720.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 7, odds: 1046.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 8, odds: 316.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 9, odds: 257.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 10, odds: 1664.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 11, odds: 4450.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 12, odds: 117.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 13, odds: 1534.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 14, odds: 61.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 15, odds: 204.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 3, horse_number_3: 16, odds: 2390.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 5, odds: 245.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 6, odds: 358.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 7, odds: 744.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 8, odds: 178.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 9, odds: 207.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 10, odds: 1051.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 11, odds: 3784.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 12, odds: 64.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 13, odds: 1871.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 14, odds: 38.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 15, odds: 206.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 4, horse_number_3: 16, odds: 1837.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 6, odds: 605.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 7, odds: 2118.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 8, odds: 372.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 9, odds: 331.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 10, odds: 2157.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 11, odds: 6047.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 12, odds: 146.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 13, odds: 5706.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 14, odds: 74.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 15, odds: 304.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 5, horse_number_3: 16, odds: 2700.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 7, odds: 3023.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 8, odds: 541.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 9, odds: 693.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 10, odds: 2406.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 11, odds: 5615.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 12, odds: 249.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 13, odds: 5165.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 14, odds: 133.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 15, odds: 442.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 6, horse_number_3: 16, odds: 4114.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 7, horse_number_3: 8, odds: 2099.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 7, horse_number_3: 9, odds: 1541.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 7, horse_number_3: 10, odds: 3628.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 7, horse_number_3: 11, odds: 8845.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 7, horse_number_3: 12, odds: 524.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 7, horse_number_3: 13, odds: 5090.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 7, horse_number_3: 14, odds: 302.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 7, horse_number_3: 15, odds: 827.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 7, horse_number_3: 16, odds: 8133.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 8, horse_number_3: 9, odds: 319.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 8, horse_number_3: 10, odds: 1760.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 8, horse_number_3: 11, odds: 6675.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 8, horse_number_3: 12, odds: 117.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 8, horse_number_3: 13, odds: 3975.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 8, horse_number_3: 14, odds: 71.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 8, horse_number_3: 15, odds: 266.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 8, horse_number_3: 16, odds: 2010.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 9, horse_number_3: 10, odds: 1842.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 9, horse_number_3: 11, odds: 5996.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 9, horse_number_3: 12, odds: 94.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 9, horse_number_3: 13, odds: 4422.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 9, horse_number_3: 14, odds: 45.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 9, horse_number_3: 15, odds: 211.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 9, horse_number_3: 16, odds: 2343.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 10, horse_number_3: 11, odds: 17258.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 10, horse_number_3: 12, odds: 628.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 10, horse_number_3: 13, odds: 15382.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 10, horse_number_3: 14, odds: 340.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 10, horse_number_3: 15, odds: 1590.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 10, horse_number_3: 16, odds: 7370.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 11, horse_number_3: 12, odds: 2591.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 11, horse_number_3: 13, odds: 9827.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 11, horse_number_3: 14, odds: 1298.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 11, horse_number_3: 15, odds: 3887.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 11, horse_number_3: 16, odds: 17258.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 12, horse_number_3: 13, odds: 1171.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 12, horse_number_3: 14, odds: 16.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 12, horse_number_3: 15, odds: 81.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 12, horse_number_3: 16, odds: 784.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 13, horse_number_3: 14, odds: 749.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 13, horse_number_3: 15, odds: 2297.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 13, horse_number_3: 16, odds: 12865.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 14, horse_number_3: 15, odds: 42.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 14, horse_number_3: 16, odds: 436.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 1, horse_number_2: 15, horse_number_3: 16, odds: 1857.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 4, odds: 397.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 5, odds: 661.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 6, odds: 1274.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 7, odds: 3158.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 8, odds: 722.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 9, odds: 530.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 10, odds: 5054.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 11, odds: 17258.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 12, odds: 228.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 13, odds: 2819.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 14, odds: 117.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 15, odds: 612.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 3, horse_number_3: 16, odds: 4846.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 5, odds: 423.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 6, odds: 633.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 7, odds: 2440.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 8, odds: 485.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 9, odds: 414.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 10, odds: 2911.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 11, odds: 13607.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 12, odds: 126.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 13, odds: 5706.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 14, odds: 75.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 15, odds: 549.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 4, horse_number_3: 16, odds: 4237.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 6, odds: 974.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 7, odds: 4395.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 8, odds: 822.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 9, odds: 675.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 10, odds: 3931.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 11, odds: 16847.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 12, odds: 270.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 13, odds: 9071.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 14, odds: 125.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 15, odds: 863.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 5, horse_number_3: 16, odds: 6153.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 7, odds: 4686.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 8, odds: 909.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 9, odds: 1211.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 10, odds: 3866.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 11, odds: 14152.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 12, odds: 412.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 13, odds: 13103.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 14, odds: 213.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 15, odds: 1298.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 6, horse_number_3: 16, odds: 8845.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 7, horse_number_3: 8, odds: 4395.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 7, horse_number_3: 9, odds: 2807.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 7, horse_number_3: 10, odds: 13874.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 7, horse_number_3: 11, odds: 24400.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 7, horse_number_3: 12, odds: 1209.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 7, horse_number_3: 13, odds: 21442.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 7, horse_number_3: 14, odds: 687.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 7, horse_number_3: 15, odds: 3011.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 7, horse_number_3: 16, odds: 22112.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 8, horse_number_3: 9, odds: 714.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 8, horse_number_3: 10, odds: 3666.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 8, horse_number_3: 11, odds: 19655.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 8, horse_number_3: 12, odds: 248.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 8, horse_number_3: 13, odds: 8957.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 8, horse_number_3: 14, odds: 126.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 8, horse_number_3: 15, odds: 753.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 8, horse_number_3: 16, odds: 6937.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 9, horse_number_3: 10, odds: 3845.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 9, horse_number_3: 11, odds: 9189.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 9, horse_number_3: 12, odds: 184.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 9, horse_number_3: 13, odds: 6262.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 9, horse_number_3: 14, odds: 101.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 9, horse_number_3: 15, odds: 572.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 9, horse_number_3: 16, odds: 4211.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 10, horse_number_3: 11, odds: 54431.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 10, horse_number_3: 12, odds: 1528.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 10, horse_number_3: 13, odds: 41624.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 10, horse_number_3: 14, odds: 899.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 10, horse_number_3: 15, odds: 5443.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 10, horse_number_3: 16, odds: 19655.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 11, horse_number_3: 12, odds: 6803.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 11, horse_number_3: 13, odds: 54431.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 11, horse_number_3: 14, odds: 4422.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 11, horse_number_3: 15, odds: 12635.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 11, horse_number_3: 16, odds: 16456.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 12, horse_number_3: 13, odds: 2327.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 12, horse_number_3: 14, odds: 30.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 12, horse_number_3: 15, odds: 205.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 12, horse_number_3: 16, odds: 1709.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 13, horse_number_3: 14, odds: 1586.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 13, horse_number_3: 15, odds: 6262.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 13, horse_number_3: 16, odds: 27215.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 14, horse_number_3: 15, odds: 106.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 14, horse_number_3: 16, odds: 934.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 2, horse_number_2: 15, horse_number_3: 16, odds: 4846.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 5, odds: 466.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 6, odds: 888.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 7, odds: 1195.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 8, odds: 460.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 9, odds: 488.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 10, odds: 1769.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 11, odds: 13103.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 12, odds: 130.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 13, odds: 1842.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 14, odds: 88.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 15, odds: 461.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 4, horse_number_3: 16, odds: 3231.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 6, odds: 1195.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 7, odds: 3647.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 8, odds: 776.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 9, odds: 727.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 10, odds: 2327.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 11, odds: 14741.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 12, odds: 274.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 13, odds: 1982.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 14, odds: 137.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 15, odds: 683.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 5, horse_number_3: 16, odds: 5320.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 7, odds: 5090.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 8, odds: 1150.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 9, odds: 1211.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 10, odds: 4624.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 11, odds: 28304.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 12, odds: 410.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 13, odds: 4090.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 14, odds: 229.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 15, odds: 1033.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 6, horse_number_3: 16, odds: 9693.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 7, horse_number_3: 8, odds: 4187.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 7, horse_number_3: 9, odds: 2650.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 7, horse_number_3: 10, odds: 4020.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 7, horse_number_3: 11, odds: 26207.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 7, horse_number_3: 12, odds: 946.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 7, horse_number_3: 13, odds: 3887.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 7, horse_number_3: 14, odds: 710.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 7, horse_number_3: 15, odds: 1274.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 7, horse_number_3: 16, odds: 12635.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 8, horse_number_3: 9, odds: 807.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 8, horse_number_3: 10, odds: 3076.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 8, horse_number_3: 11, odds: 17258.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 8, horse_number_3: 12, odds: 239.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 8, horse_number_3: 13, odds: 2415.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 8, horse_number_3: 14, odds: 138.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 8, horse_number_3: 15, odds: 605.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 8, horse_number_3: 16, odds: 5528.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 9, horse_number_3: 10, odds: 3485.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 9, horse_number_3: 11, odds: 10561.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 9, horse_number_3: 12, odds: 207.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 9, horse_number_3: 13, odds: 2774.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 9, horse_number_3: 14, odds: 101.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 9, horse_number_3: 15, odds: 507.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 9, horse_number_3: 16, odds: 4090.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 10, horse_number_3: 11, odds: 35380.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 10, horse_number_3: 12, odds: 787.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 10, horse_number_3: 13, odds: 2335.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 10, horse_number_3: 14, odds: 582.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 10, horse_number_3: 15, odds: 2112.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 10, horse_number_3: 16, odds: 10255.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 11, horse_number_3: 12, odds: 6613.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 11, horse_number_3: 13, odds: 14152.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 11, horse_number_3: 14, odds: 3591.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 11, horse_number_3: 15, odds: 9827.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 11, horse_number_3: 16, odds: 32164.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 12, horse_number_3: 13, odds: 839.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 12, horse_number_3: 14, odds: 35.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 12, horse_number_3: 15, odds: 172.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 12, horse_number_3: 16, odds: 1480.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 13, horse_number_3: 14, odds: 739.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 13, horse_number_3: 15, odds: 1366.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 13, horse_number_3: 16, odds: 7448.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 14, horse_number_3: 15, odds: 88.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 14, horse_number_3: 16, odds: 877.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 3, horse_number_2: 15, horse_number_3: 16, odds: 3724.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 6, odds: 476.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 7, odds: 1998.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 8, odds: 319.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 9, odds: 326.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 10, odds: 1438.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 11, odds: 7370.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 12, odds: 116.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 13, odds: 4948.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 14, odds: 71.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 15, odds: 450.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 5, horse_number_3: 16, odds: 2573.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 7, odds: 2660.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 8, odds: 462.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 9, odds: 779.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 10, odds: 1568.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 11, odds: 14441.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 12, odds: 199.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 13, odds: 8041.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 14, odds: 128.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 15, odds: 703.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 6, horse_number_3: 16, odds: 4450.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 7, horse_number_3: 8, odds: 2105.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 7, horse_number_3: 9, odds: 1976.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 7, horse_number_3: 10, odds: 2876.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 7, horse_number_3: 11, odds: 11231.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 7, horse_number_3: 12, odds: 547.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 7, horse_number_3: 13, odds: 3666.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 7, horse_number_3: 14, odds: 336.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 7, horse_number_3: 15, odds: 947.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 7, horse_number_3: 16, odds: 13607.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 8, horse_number_3: 9, odds: 440.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 8, horse_number_3: 10, odds: 1474.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 8, horse_number_3: 11, odds: 9827.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 8, horse_number_3: 12, odds: 101.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 8, horse_number_3: 13, odds: 4187.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 8, horse_number_3: 14, odds: 63.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 8, horse_number_3: 15, odds: 374.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 8, horse_number_3: 16, odds: 2456.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 9, horse_number_3: 10, odds: 2680.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 9, horse_number_3: 11, odds: 9071.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 9, horse_number_3: 12, odds: 116.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 9, horse_number_3: 13, odds: 5203.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 9, horse_number_3: 14, odds: 63.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 9, horse_number_3: 15, odds: 364.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 9, horse_number_3: 16, odds: 3647.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 10, horse_number_3: 11, odds: 32164.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 10, horse_number_3: 12, odds: 546.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 10, horse_number_3: 13, odds: 14441.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 10, horse_number_3: 14, odds: 328.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 10, horse_number_3: 15, odds: 1791.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 10, horse_number_3: 16, odds: 9693.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 11, horse_number_3: 12, odds: 3704.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 11, horse_number_3: 13, odds: 39311.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 11, horse_number_3: 14, odds: 2491.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 11, horse_number_3: 15, odds: 9434.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 11, horse_number_3: 16, odds: 39311.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 12, horse_number_3: 13, odds: 1024.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 12, horse_number_3: 14, odds: 15.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 12, horse_number_3: 15, odds: 109.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 12, horse_number_3: 16, odds: 657.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 13, horse_number_3: 14, odds: 746.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 13, horse_number_3: 15, odds: 3050.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 13, horse_number_3: 16, odds: 11993.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 14, horse_number_3: 15, odds: 71.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 14, horse_number_3: 16, odds: 427.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 4, horse_number_2: 15, horse_number_3: 16, odds: 2830.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 7, odds: 3036.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 8, odds: 834.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 9, odds: 1034.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 10, odds: 2491.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 11, odds: 13607.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 12, odds: 335.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 13, odds: 8957.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 14, odds: 184.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 15, odds: 1039.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 6, horse_number_3: 16, odds: 7147.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 7, horse_number_3: 8, odds: 3724.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 7, horse_number_3: 9, odds: 3158.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 7, horse_number_3: 10, odds: 11993.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 7, horse_number_3: 11, odds: 28304.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 7, horse_number_3: 12, odds: 1209.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 7, horse_number_3: 13, odds: 18621.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 7, horse_number_3: 14, odds: 722.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 7, horse_number_3: 15, odds: 3158.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 7, horse_number_3: 16, odds: 22112.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 8, horse_number_3: 9, odds: 719.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 8, horse_number_3: 10, odds: 2456.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 8, horse_number_3: 11, odds: 16456.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 8, horse_number_3: 12, odds: 228.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 8, horse_number_3: 13, odds: 7370.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 8, horse_number_3: 14, odds: 120.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 8, horse_number_3: 15, odds: 664.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 8, horse_number_3: 16, odds: 5443.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 9, horse_number_3: 10, odds: 2764.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 9, horse_number_3: 11, odds: 9966.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 9, horse_number_3: 12, odds: 213.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 9, horse_number_3: 13, odds: 7006.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 9, horse_number_3: 14, odds: 110.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 9, horse_number_3: 15, odds: 653.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 9, horse_number_3: 16, odds: 4314.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 10, horse_number_3: 11, odds: 41624.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 10, horse_number_3: 12, odds: 999.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 10, horse_number_3: 13, odds: 23587.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 10, horse_number_3: 14, odds: 657.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 10, horse_number_3: 15, odds: 3076.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 10, horse_number_3: 16, odds: 16082.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 11, horse_number_3: 12, odds: 5571.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 11, horse_number_3: 13, odds: 58967.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 11, horse_number_3: 14, odds: 4749.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 11, horse_number_3: 15, odds: 12865.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 11, horse_number_3: 16, odds: 29483.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 12, horse_number_3: 13, odds: 2406.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 12, horse_number_3: 14, odds: 34.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 12, horse_number_3: 15, odds: 223.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 12, horse_number_3: 16, odds: 1579.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 13, horse_number_3: 14, odds: 1657.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 13, horse_number_3: 15, odds: 6047.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 13, horse_number_3: 16, odds: 22112.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 14, horse_number_3: 15, odds: 121.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 14, horse_number_3: 16, odds: 841.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 5, horse_number_2: 15, horse_number_3: 16, odds: 4717.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 7, horse_number_3: 8, odds: 3322.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 7, horse_number_3: 9, odds: 5241.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 7, horse_number_3: 10, odds: 10886.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 7, horse_number_3: 11, odds: 29483.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 7, horse_number_3: 12, odds: 1902.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 7, horse_number_3: 13, odds: 18621.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 7, horse_number_3: 14, odds: 1119.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 7, horse_number_3: 15, odds: 3931.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 7, horse_number_3: 16, odds: 19124.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 8, horse_number_3: 9, odds: 1117.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 8, horse_number_3: 10, odds: 1423.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 8, horse_number_3: 11, odds: 16082.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 8, horse_number_3: 12, odds: 317.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 8, horse_number_3: 13, odds: 10108.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 8, horse_number_3: 14, odds: 184.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 8, horse_number_3: 15, odds: 946.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 8, horse_number_3: 16, odds: 6613.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 9, horse_number_3: 10, odds: 4813.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 9, horse_number_3: 11, odds: 15724.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 9, horse_number_3: 12, odds: 418.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 9, horse_number_3: 13, odds: 14152.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 9, horse_number_3: 14, odds: 215.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 9, horse_number_3: 15, odds: 1124.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 9, horse_number_3: 16, odds: 9071.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 10, horse_number_3: 11, odds: 39311.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 10, horse_number_3: 12, odds: 1342.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 10, horse_number_3: 13, odds: 32164.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 10, horse_number_3: 14, odds: 922.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 10, horse_number_3: 15, odds: 3628.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 10, horse_number_3: 16, odds: 11231.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 11, horse_number_3: 12, odds: 12200.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 11, horse_number_3: 13, odds: 44225.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 11, horse_number_3: 14, odds: 5706.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 11, horse_number_3: 15, odds: 22112.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 11, horse_number_3: 16, odds: 32164.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 12, horse_number_3: 13, odds: 3824.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 12, horse_number_3: 14, odds: 54.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 12, horse_number_3: 15, odds: 313.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 12, horse_number_3: 16, odds: 2753.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 13, horse_number_3: 14, odds: 2204.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 13, horse_number_3: 15, odds: 10721.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 13, horse_number_3: 16, odds: 35380.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 14, horse_number_3: 15, odds: 166.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 14, horse_number_3: 16, odds: 1575.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 6, horse_number_2: 15, horse_number_3: 16, odds: 6937.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 8, horse_number_3: 9, odds: 3555.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 8, horse_number_3: 10, odds: 9071.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 8, horse_number_3: 11, odds: 37242.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 8, horse_number_3: 12, odds: 1123.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 8, horse_number_3: 13, odds: 19655.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 8, horse_number_3: 14, odds: 684.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 8, horse_number_3: 15, odds: 2785.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 8, horse_number_3: 16, odds: 20812.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 9, horse_number_3: 10, odds: 13351.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 9, horse_number_3: 11, odds: 21442.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 9, horse_number_3: 12, odds: 1012.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 9, horse_number_3: 13, odds: 13607.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 9, horse_number_3: 14, odds: 532.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 9, horse_number_3: 15, odds: 2063.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 9, horse_number_3: 16, odds: 13607.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 10, horse_number_3: 11, odds: 47174.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 10, horse_number_3: 12, odds: 3866.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 10, horse_number_3: 13, odds: 20812.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 10, horse_number_3: 14, odds: 2660.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 10, horse_number_3: 15, odds: 6047.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 10, horse_number_3: 16, odds: 33695.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 11, horse_number_3: 12, odds: 16847.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 11, horse_number_3: 13, odds: 35380.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 11, horse_number_3: 14, odds: 10721.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 11, horse_number_3: 15, odds: 18621.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 11, horse_number_3: 16, odds: 54431.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 12, horse_number_3: 13, odds: 8133.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 12, horse_number_3: 14, odds: 157.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 12, horse_number_3: 15, odds: 711.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 12, horse_number_3: 16, odds: 5752.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 13, horse_number_3: 14, odds: 5127.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 13, horse_number_3: 15, odds: 4594.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 13, horse_number_3: 16, odds: 21442.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 14, horse_number_3: 15, odds: 485.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 14, horse_number_3: 16, odds: 3887.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 7, horse_number_2: 15, horse_number_3: 16, odds: 9966.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 9, horse_number_3: 10, odds: 2888.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 9, horse_number_3: 11, odds: 14741.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 9, horse_number_3: 12, odds: 246.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 9, horse_number_3: 13, odds: 8041.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 9, horse_number_3: 14, odds: 131.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 9, horse_number_3: 15, odds: 597.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 9, horse_number_3: 16, odds: 5165.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 10, horse_number_3: 11, odds: 35380.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 10, horse_number_3: 12, odds: 866.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 10, horse_number_3: 13, odds: 20812.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 10, horse_number_3: 14, odds: 552.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 10, horse_number_3: 15, odds: 2650.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 10, horse_number_3: 16, odds: 10721.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 11, horse_number_3: 12, odds: 6100.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 11, horse_number_3: 13, odds: 47174.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 11, horse_number_3: 14, odds: 4913.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 11, horse_number_3: 15, odds: 9189.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 11, horse_number_3: 16, odds: 35380.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 12, horse_number_3: 13, odds: 1847.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 12, horse_number_3: 14, odds: 29.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 12, horse_number_3: 15, odds: 187.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 12, horse_number_3: 16, odds: 947.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 13, horse_number_3: 14, odds: 1310.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 13, horse_number_3: 15, odds: 3866.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 13, horse_number_3: 16, odds: 25271.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 14, horse_number_3: 15, odds: 108.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 14, horse_number_3: 16, odds: 686.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 8, horse_number_2: 15, horse_number_3: 16, odds: 4138.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 10, horse_number_3: 11, odds: 24400.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 10, horse_number_3: 12, odds: 1167.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 10, horse_number_3: 13, odds: 14152.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 10, horse_number_3: 14, odds: 681.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 10, horse_number_3: 15, odds: 3173.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 10, horse_number_3: 16, odds: 10721.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 11, horse_number_3: 12, odds: 5203.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 11, horse_number_3: 13, odds: 25271.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 11, horse_number_3: 14, odds: 2350.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 11, horse_number_3: 15, odds: 10886.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 11, horse_number_3: 16, odds: 20217.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 12, horse_number_3: 13, odds: 2204.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 12, horse_number_3: 14, odds: 27.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 12, horse_number_3: 15, odds: 158.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 12, horse_number_3: 16, odds: 1392.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 13, horse_number_3: 14, odds: 1191.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 13, horse_number_3: 15, odds: 5401.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 13, horse_number_3: 16, odds: 16082.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 14, horse_number_3: 15, odds: 79.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 14, horse_number_3: 16, odds: 782.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 9, horse_number_2: 15, horse_number_3: 16, odds: 3187.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 11, horse_number_3: 12, odds: 19124.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 11, horse_number_3: 13, odds: 39311.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 11, horse_number_3: 14, odds: 13874.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 11, horse_number_3: 15, odds: 28304.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 11, horse_number_3: 16, odds: 44225.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 12, horse_number_3: 13, odds: 5996.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 12, horse_number_3: 14, odds: 141.0),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 12, horse_number_3: 15, odds: 999.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 12, horse_number_3: 16, odds: 4211.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 13, horse_number_3: 14, odds: 4846.6),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 13, horse_number_3: 15, odds: 13607.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 13, horse_number_3: 16, odds: 26207.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 14, horse_number_3: 15, odds: 624.5),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 14, horse_number_3: 16, odds: 2563.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 10, horse_number_2: 15, horse_number_3: 16, odds: 14741.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 12, horse_number_3: 13, odds: 18143.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 12, horse_number_3: 14, odds: 671.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 12, horse_number_3: 15, odds: 4237.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 12, horse_number_3: 16, odds: 22826.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 13, horse_number_3: 14, odds: 13351.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 13, horse_number_3: 15, odds: 17690.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 13, horse_number_3: 16, odds: 32164.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 14, horse_number_3: 15, odds: 2611.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 14, horse_number_3: 16, odds: 13874.7),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 11, horse_number_2: 15, horse_number_3: 16, odds: 18621.3),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 12, horse_number_2: 13, horse_number_3: 14, odds: 247.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 12, horse_number_2: 13, horse_number_3: 15, odds: 1315.2),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 12, horse_number_2: 13, horse_number_3: 16, odds: 6613.1),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 12, horse_number_2: 14, horse_number_3: 15, odds: 25.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 12, horse_number_2: 14, horse_number_3: 16, odds: 164.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 12, horse_number_2: 15, horse_number_3: 16, odds: 1133.9),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 13, horse_number_2: 14, horse_number_3: 15, odds: 846.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 13, horse_number_2: 14, horse_number_3: 16, odds: 3555.8),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 13, horse_number_2: 15, horse_number_3: 16, odds: 8629.4),
        have_attributes(race_meta_id: @meta.id, horse_number_1: 14, horse_number_2: 15, horse_number_3: 16, odds: 565.1),
      ]
    end
  end
end
